/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.json.JSONObject;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author morriscao
 */
public class NewJFrame extends javax.swing.JFrame {
	
	public String vrResult = "识别失败。";

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_rec_result = new javax.swing.JTextField();
        jButton_send = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_nlp_result = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_answer_result = new javax.swing.JTextArea();

        jFileChooser.setFileFilter(getWavFileFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("输入"));

        jLabel1.setText("文本输入");

        jTextField_rec_result.setText("今天是周几？");

        jButton_send.setText("send");
        jButton_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addGap(22)
        			.addComponent(jTextField_rec_result, GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButton_send, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)
        			.addGap(2))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(jTextField_rec_result, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton_send))
        			.addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("语义输出"));

        jTextArea_nlp_result.setColumns(20);
        jTextArea_nlp_result.setRows(5);
        jScrollPane1.setViewportView(jTextArea_nlp_result);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );

             
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("结果输出"));

        jTextArea_answer_result.setColumns(20);
        jTextArea_answer_result.setRows(5);
        jScrollPane2.setViewportView(jTextArea_answer_result);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
        		jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel3Layout.setVerticalGroup(
        		jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                	.addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FileNameExtensionFilter getWavFileFilter() {
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("Wav File(*.wav)", "wav");
        return fileFilter;
    }

    private String formatJson(String oldJson) {
        int i = 0;
	    String space = "  ";
	    String formatJson = "";
	    int indentCount = 0;
	    Boolean isStr = false;
	    String currChar = "";
	
	    for (i = 0; i < oldJson.length(); i++) {
		    currChar = oldJson.substring(i, i+1);
		    switch (currChar) {
			    case "{":
			    case "[":
				    if (!isStr) {
					    indentCount++;
					    formatJson += currChar + appendJson(space, indentCount);
				    } else {
					    formatJson += currChar;
				    }
				    break;
			    case "}":
			    case "]":
				    if (!isStr) {
					    indentCount--;
					    formatJson += appendJson(space, indentCount) + currChar;
				    } else {
					    formatJson += currChar;
				    }
				    break;
			    case ",":
				    if (!isStr) {
					    formatJson += "," + appendJson(space, indentCount);
				    } else {
					    formatJson += currChar;
				    }
				    break;
			    case ":":
				    if (!isStr) {
					    formatJson += ": ";
				    } else {
					    formatJson += currChar;
				    }
				    break;
			    case " ":
			    case "\n":
			    case "\t":
				    if (isStr) {
					    formatJson += currChar;
				    }
				    break;
			    case "\"":
				    if (i > 0 && !oldJson.substring(i - 1, i).equals("\\")) {
					    isStr = !isStr;
				    }
				    formatJson += currChar;
				    break;
			    default:
				    formatJson += currChar;
				    break;
		    }
	    }
	    return formatJson;
    }

    private String appendJson(String str, int count) {
        //String retStr = "\n";
        String retStr = System.getProperty("line.separator", "\n");
        for (int i = 0; i < count; i++) {
            retStr += str;
        }
        return retStr;
    }
    
    private void jButton_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendActionPerformed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(this, "123", "456",JOptionPane.WARNING_MESSAGE);
    	JSONObject result = NLIProcess.process(jTextField_rec_result.getText());
    	jTextArea_nlp_result.setText(result.toString());
        jTextArea_nlp_result.setText(formatJson(jTextArea_nlp_result.getText()));
        JSONObject answer = SemanticProcess.process(result);
        jTextArea_answer_result.setText(answer.toString());
        jTextArea_answer_result.setText(formatJson(jTextArea_answer_result.getText()));
    }//GEN-LAST:event_jButton_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJFrame frame = new NewJFrame();
                // show center
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }
    private javax.swing.JButton jButton_send;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_answer_result;
    private javax.swing.JTextArea jTextArea_nlp_result;
    private javax.swing.JTextField jTextField_rec_result;
    // End of variables declaration//GEN-END:variables
}
